browser = chrome
environment = staging

//UTM_Strings
affiliateString = ?utm_source=testing&utm_medium=banner&utm_campaign=QA&uadgroup=uadgrouptest&uAdCampgn=uadcampgntest&utm_term=urefkeywordtest&utm_content=urefmediatypetest&gclid=gclidtest&lpvariant=lpvarianttest
utmString = ?utm_source=audience&utm_medium=banner&utm_campaign=QA&uadgroup=uadgrouptest&uAdCampgn=uadcampgntest&utm_term=urefkeywordtest&utm_content=urefmediatypetest&gclid=gclidtest&lpvariant=lpvarianttest

//TestDataFile
sitedetails= TestData

//LeadDataFile
leadData= AutomationLeads

//Student_Details
firstname = Robtest
lastname = Grajtest
country = Austria
phone = 5189011001
zip = 12345
