<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CloseButton</name>
   <tag></tag>
   <elementGuidId>0bf684d8-f924-4ce1-bd1a-05193708ca26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//embeddedservice-chat-header/header/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
