<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Done</name>
   <tag></tag>
   <elementGuidId>7efbc552-b0e4-48af-a614-b6b7eaf9eb30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c15b0fe-f01c-49b9-ba1b-742aa57711e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>2890f60e-2ced-4291-acac-d0fbc6eeb1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> label bBody</value>
      <webElementGuid>53103667-66b1-4890-a299-e7011b0e72f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>7:161;a</value>
      <webElementGuid>95a1654e-dc28-447e-aa12-44745e8f9644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>7280fa99-4b47-4903-a8bd-c9033b7524af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;modalContainer sidebarMaximized layout-docked embeddedServiceSidebar&quot;]/div[@class=&quot;dockableContainer showDockableContainer&quot;]/div[@class=&quot;sidebarBody&quot;]/div[@class=&quot;activeFeature hideWhileLoading&quot;]/div[@class=&quot;featureBody embeddedServiceSidebarFeature&quot;]/div[@class=&quot;stateBody embeddedServiceSidebarState embeddedServiceSidebarDialogState&quot;]/div[@class=&quot;dialogState&quot;]/div[@class=&quot;dialogButtonContainer&quot;]/button[@class=&quot;dialogButton dialog-button-0 uiButton--default uiButton embeddedServiceSidebarButton&quot;]/span[@class=&quot;label bBody&quot;]</value>
      <webElementGuid>4867b0a6-d8c9-44fd-bd54-da3a0dae0178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='container']/div[5]/div/div/div[2]/div/div/div/div[2]/button/span</value>
      <webElementGuid>6bb5469e-ac9f-4208-bb6d-a5b4d1ea882d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We logged your case. You’ll hear back from us soon.'])[1]/following::span[1]</value>
      <webElementGuid>e958dccc-b6be-4e3e-9908-5b2b7827c978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case submitted'])[1]/following::span[1]</value>
      <webElementGuid>f3f4ad9f-7bbb-4cda-bdf5-ca43d11178f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>92f3d1d1-7281-4bd2-91ff-dcec0fb9c21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button/span</value>
      <webElementGuid>81691238-329a-405d-824b-78cbb277a153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>958b447e-787a-4da3-9a8c-8c689da2684e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
