<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit</name>
   <tag></tag>
   <elementGuidId>40ae39e7-0f85-41f8-9346-d564976869a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4d7f2570-f276-4c21-8f81-1f216a73104d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>27f2846a-98fd-4325-9052-e416faf151ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> label bBody</value>
      <webElementGuid>f9463a6e-f9b3-431b-9553-0872df231231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>247:0</value>
      <webElementGuid>3d4a6fea-8888-4823-8e80-cff0d456a1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>2d06f070-4804-4720-9d60-d8b12558c711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;modalContainer sidebarMaximized layout-docked embeddedServiceSidebar&quot;]/div[@class=&quot;dockableContainer showDockableContainer&quot;]/div[@class=&quot;sidebarBody&quot;]/div[@class=&quot;activeFeature hideWhileLoading&quot;]/div[@class=&quot;featureBody embeddedServiceSidebarFeature embeddedServiceLiveAgentSidebarFeature&quot;]/div[@class=&quot;stateBody embeddedServiceSidebarState&quot;]/div[@class=&quot;offlineSupportUI embeddedServiceLiveAgentStateOfflineSupportDefaultUI&quot;]/div[@class=&quot;buttonWrapper embeddedServiceSidebarForm&quot;]/button[@class=&quot;submitButton uiButton--default uiButton embeddedServiceSidebarButton&quot;]/span[@class=&quot;label bBody&quot;]</value>
      <webElementGuid>c34e927b-5f81-45b0-be82-3df5a4b87d52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='container']/div[5]/div/div/div[2]/div/div/div/div[2]/button/span</value>
      <webElementGuid>bce493d9-713b-44df-aa8c-15794a672156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[1]</value>
      <webElementGuid>a617788c-e0ca-4789-af9d-48c51c8c6dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message'])[1]/following::span[2]</value>
      <webElementGuid>a532bb93-819c-44dd-9970-996f592e1dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>3088eedc-a071-48ff-9988-2f84363167a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button/span</value>
      <webElementGuid>b1f2c1b9-e593-4b85-92fd-29c95ddb6921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>2ca15942-0154-4561-b716-f8c096f675d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
